"""Converts LanguageTool pattern XML into Vale existence rules.

A rule is emitted when every one of its tokens is literal, a regex, or an
inflected form the lemma index can expand. Anything needing part-of-speech
tagging is counted and skipped, because Vale matches text and cannot ask a
tagger.

Usage: lt_xml.py OUT.yml MESSAGE LEVEL LEMMAS.tsv SOURCE.xml [more.xml]
"""

import re
import sys
import xml.etree.ElementTree as ET

MAX_FORMS = 40  # a lemma with more forms than this makes an unreadable regex


def load_lemmas(path):
    index = {}
    try:
        with open(path, encoding="utf-8") as fh:
            for line in fh:
                lemma, _, forms = line.partition("\t")
                if lemma:
                    index[lemma] = forms.split()
    except OSError:
        pass
    return index


MIN_LITERAL = 6      # below this a mandatory match is too broad to mean anything
MIN_ALTERNATIVE = 3  # single-letter alternatives match half the language


def token_regex(token, lemmas):
    """Returns (regex, mandatory, shortest_literal) or None if not expressible."""
    if token.get("postag") or token.get("postag_regexp"):
        return None
    for child in token:
        if child.tag in ("exception", "match"):
            return None

    text = (token.text or "").strip()
    if not text:
        return None

    if token.get("inflected") == "yes":
        stems = text.split("|") if token.get("regexp") == "yes" else [text]
        forms = []
        for stem in stems:
            if not re.fullmatch(r"[^\\\[\](){}*+?.^$|]+", stem):
                return None
            got = lemmas.get(stem)
            if not got:
                return None
            forms.extend(got)
        forms = sorted(set(forms))
        if not forms or len(forms) > MAX_FORMS:
            return None
        body = "|".join(re.escape(f) for f in forms)
    elif token.get("regexp") == "yes":
        # Euphony rules (у/в, і/й) write "any neighbouring word" as a wildcard,
        # which outside LanguageTool's tokeniser matches whole sentences.
        if re.search(r"\.[*+{]", text):
            return None
        body = text
    else:
        body = re.escape(text)

    alternatives = [a for a in body.split("|") if a]
    if not alternatives or min(len(a) for a in alternatives) < MIN_ALTERNATIVE:
        return None

    piece = f"(?:{body})"
    if token.get("min") == "0":
        return piece + "?[ \\t]*", False, 0
    return piece, True, min(len(a) for a in alternatives)


def convert(sources, lemmas):
    rules, skipped = [], 0
    for path in sources:
        try:
            root = ET.parse(path).getroot()
        except ET.ParseError:
            continue
        for rule in root.iter("rule"):
            # Antipatterns carve exceptions out of a match, and dropping them
            # would turn a careful rule into a blunt one.
            if rule.find("antipattern") is not None:
                skipped += 1
                continue
            pattern = rule.find("pattern")
            if pattern is None:
                skipped += 1
                continue
            tokens = pattern.findall("token")
            if not tokens or len(tokens) > 6:
                skipped += 1
                continue

            parsed = [token_regex(t, lemmas) for t in tokens]
            if any(p is None for p in parsed):
                skipped += 1
                continue

            mandatory = [p for p in parsed if p[1]]
            if len(mandatory) < 2 or sum(p[2] for p in mandatory) < MIN_LITERAL:
                skipped += 1
                continue

            expr = r"[ \t]+".join(p[0] for p in parsed).replace("?[ \\t]*[ \\t]+", "?[ \\t]*")
            if len(expr) > 4000:
                skipped += 1
                continue

            message = rule.find("message")
            hints = []
            if message is not None:
                for s in message.iter("suggestion"):
                    text = "".join(s.itertext()).strip()
                    text = re.sub(r"\\\d+", "…", text)
                    if text:
                        hints.append(text)
            rules.append((expr, hints[:3]))
    return rules, skipped


def main():
    out, message, level, lemma_path, *sources = sys.argv[1:]
    lemmas = load_lemmas(lemma_path)
    rules, skipped = convert(sources, lemmas)

    seen, lines = set(), []
    for expr, hints in rules:
        if expr in seen:
            continue
        seen.add(expr)
        if hints:
            lines.append(f"  # {' / '.join(hints)}")
        lines.append("  - '" + expr.replace("'", "''") + "'")

    with open(out, "w", encoding="utf-8") as fh:
        fh.write("# Generated by generators/uk-lt-xml.sh from LanguageTool (LGPL-2.1). Do not edit.\n")
        fh.write(f"# {len(seen)} rules converted, {skipped} skipped as needing a tagger.\n")
        fh.write("extends: existence\n")
        fh.write(f'message: "{message}"\n')
        fh.write(f"level: {level}\n")
        fh.write("ignorecase: true\n")
        fh.write("nonword: true\n")
        fh.write("tokens:\n")
        fh.write("\n".join(lines) + "\n")

    print(f"stet: {len(seen)} rules converted, {skipped} skipped", file=sys.stderr)


if __name__ == "__main__":
    main()
