"""Cuts measured constructions into a shared base and one rule set per register.

Reads the excess ratios in data/uk-excess.tsv and the expressions in
tools/patterns-uk.tsv. A construction that runs high in every register belongs to
the base; one that runs high only in some belongs to those presets alone. The
bands below are thresholds on excess frequency, machine rate over human rate.

    presets.py PATTERNS.tsv EXCESS.tsv STYLES_DIR LANG
"""

import collections
import os
import sys

BASE_MIN = 4.0     # high everywhere: no preset needs to repeat it
PRESET_MIN = 2.0   # below this the construction is not a marker in that register
BANDS = [(8.0, "error"), (4.0, "warning"), (PRESET_MIN, "suggestion")]

# Brown category letters are opaque to anyone but the corpus, so the registry
# publishes a readable code instead.
PRESETS = {
    "H": ("Official", "official", "ділове й офіційне"),
    "A": ("Press", "press", "публіцистика та медіа"),
    "I": ("Academic", "academic", "наукове й фахове"),
    "docs": ("Docs", "docs", "технічна документація та інструкції"),
    "informal": ("Informal", "informal", "розмовне, підтримка, листування"),
    "fiction": ("Fiction", "fiction", "художня література"),
}

PRELIMINARY = {"fiction"}  # control corpus still too small to trust


def level_for(excess):
    for floor, name in BANDS:
        if excess >= floor:
            return name
    return None


def load_patterns(path):
    out = {}
    for line in open(path, encoding="utf-8"):
        line = line.rstrip("\n")
        if line and not line.startswith("#"):
            label, _, expr = line.partition("\t")
            out[label] = expr
    return out


def load_excess(path):
    rows = collections.defaultdict(dict)
    notes = []
    for line in open(path, encoding="utf-8"):
        line = line.rstrip("\n")
        if line.startswith("#"):
            notes.append(line.lstrip("# "))
            continue
        if not line:
            continue
        label, register, _ai, _human, excess = line.split("\t")
        rows[label][register] = float(excess)
    return rows, notes


def write_rule(path, header, message, entries):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    by_level = collections.defaultdict(list)
    for label, expr, level, excess in entries:
        by_level[level].append((label, expr, excess))

    written = 0
    for level, items in by_level.items():
        target = path.replace(".yml", f"-{level}.yml") if len(by_level) > 1 else path
        with open(target, "w", encoding="utf-8") as fh:
            fh.write(header)
            fh.write("extends: existence\n")
            fh.write(f'message: "{message}"\n')
            fh.write(f"level: {level}\n")
            fh.write("ignorecase: true\nnonword: true\ntokens:\n")
            for label, expr, excess in sorted(items, key=lambda x: -x[2]):
                fh.write(f"  # {label}, надлишок {excess:.1f}x\n")
                fh.write("  - '" + expr.replace("'", "''") + "'\n")
        written += len(items)
    return written


def main():
    patterns_path, excess_path, styles_dir, lang = sys.argv[1:5]
    patterns = load_patterns(patterns_path)
    excess, notes = load_excess(excess_path)
    provenance = f"# Generated by generators/{lang.lower()}-presets.sh from {os.path.basename(excess_path)}. Do not edit.\n"
    corpora = "\n".join(f"# {n}" for n in notes if n.startswith(("machine", "control")))

    registers = sorted({r for row in excess.values() for r in row})
    # A base means "high in every register", which says nothing when only one
    # register was measured. Such a language gets presets and no base.
    single = len([r for r in registers if r not in PRELIMINARY]) < 2
    base, per_preset = [], collections.defaultdict(list)

    for label, expr in patterns.items():
        ratios = excess.get(label)
        if not ratios:
            continue
        solid = [r for r in registers if r not in PRELIMINARY]
        values = [ratios.get(r, 0.0) for r in solid]
        if values and not single and min(values) >= BASE_MIN:
            base.append((label, expr, level_for(min(values)), min(values)))
            continue
        for register in registers:
            value = ratios.get(register, 0.0)
            level = level_for(value)
            if level:
                per_preset[register].append((label, expr, level, value))

    if not base:
        print(f"  {lang}Base: skipped, one register measured", file=sys.stderr)
    count = 0 if not base else write_rule(
        os.path.join(styles_dir, f"{lang}Base", "Slop.yml"),
        provenance + f"# Excess of at least {BASE_MIN:.0f}x in every solid register.\n{corpora}\n",
        "Машинний зворот: '%s'", base)
    if base:
        print(f"  {lang}Base: {count} constructions", file=sys.stderr)

    registry = []
    for register, entries in sorted(per_preset.items()):
        name, code, human = PRESETS.get(register, (register.title(), register, register))
        note = "# Preliminary: the control corpus for this register is small.\n" if register in PRELIMINARY else ""
        count = write_rule(
            os.path.join(styles_dir, f"{lang}{name}", "Slop.yml"),
            provenance + f"# Register: {human}.\n{note}{corpora}\n",
            "Машинний зворот для цього стилю: '%s'", entries)
        registry.append(f"{lang.lower()}|{code}|{lang}{name}|{human}"
                        + ("|preliminary" if register in PRELIMINARY else ""))
        print(f"  {lang}{name}: {count} constructions", file=sys.stderr)

    # Every language writes this file, so keep the rows the others put there.
    conf = os.path.join(os.path.dirname(styles_dir.rstrip("/")), "presets.conf")
    kept = []
    if os.path.exists(conf):
        for line in open(conf, encoding="utf-8"):
            line = line.rstrip("\n")
            if line and not line.startswith("#") and not line.startswith(f"{lang.lower()}|"):
                kept.append(line)
    with open(conf, "w", encoding="utf-8") as fh:
        fh.write("# Generated by generators/<lang>-presets.sh. lang|code|style|description\n")
        fh.write("\n".join(sorted(set(kept + registry))) + "\n")


if __name__ == "__main__":
    main()
