package cli

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/themaiby/stet/internal/build"
	"github.com/themaiby/stet/internal/registry"
	"github.com/themaiby/stet/internal/tool"
	"github.com/themaiby/stet/internal/valeconf"
	"github.com/themaiby/stet/internal/warmup"
)

// waitForWarmup bounds how long a lint run will sit behind a build another
// process started. Past this it reports rather than hangs.
const waitForWarmup = 3 * time.Minute

type lintFlags struct {
	Languages   string
	Preset      string
	Config      string
	Output      string
	ListPresets bool
	Targets     []string
}

func runLint(e *env, args []string) int {
	var f lintFlags
	f.Output = "line"

	for i := 0; i < len(args); {
		switch {
		case args[i] == "--list-presets":
			f.ListPresets = true
			i++
		case args[i] == "--":
			f.Targets = append(f.Targets, args[i+1:]...)
			i = len(args)
		default:
			matched := false
			for _, flag := range []struct {
				Name   string
				Target *string
			}{
				{"lang", &f.Languages}, {"preset", &f.Preset},
				{"config", &f.Config}, {"output", &f.Output},
			} {
				if value, used, ok := flagValue(args, i, flag.Name); ok {
					*flag.Target = value
					i += used
					matched = true
					break
				}
			}
			if !matched {
				f.Targets = append(f.Targets, args[i])
				i++
			}
		}
	}

	if f.ListPresets {
		return listPresets(e)
	}
	if len(f.Targets) == 0 {
		fmt.Fprintln(e.Err, usage)
		return 2
	}

	vale, err := tool.Resolve(tool.Vale, e.Layout, e.Client, e.Err)
	if err != nil {
		fmt.Fprintln(e.Err, err)
		return 1
	}

	state := settleWarmup(e, f.Languages)
	if state.Partial() {
		// A failed build must not pass as a clean report: the reader would
		// trust an empty result from a rule that checked nothing.
		fmt.Fprintf(e.Err, "stet: WARNING, %s\n", state.Message)
		fmt.Fprintln(e.Err, "stet: this report is PARTIAL. Run 'stet build' to see the error.")
	}

	config := f.Config
	if config == "" {
		if config, err = chooseConfig(e, f); err != nil {
			fmt.Fprintln(e.Err, err)
			return 1
		}
	}
	if _, err := os.Stat(config); err != nil {
		fmt.Fprintf(e.Err, "stet: no such config: %s\n", config)
		return 1
	}
	syncPackages(e, vale, config)

	cmd := exec.Command(vale, append([]string{
		"--no-exit", "--config=" + config, "--output=" + f.Output,
	}, f.Targets...)...)
	cmd.Stdout, cmd.Stderr, cmd.Stdin = e.Out, e.Err, os.Stdin
	if err := cmd.Run(); err != nil {
		if code, ok := exitCode(err); ok {
			return code
		}
		fmt.Fprintln(e.Err, err)
		return 1
	}
	return 0
}

// chooseConfig settles which policy applies. An explicit language wins, then a
// project's own .vale.ini above the target, and only then every registered
// language, which is the widest reading and the least likely to be what the
// project meant.
func chooseConfig(e *env, f lintFlags) (string, error) {
	languages, err := loadLanguages(e)
	if err != nil {
		return "", err
	}

	if f.Languages == "" {
		// A project's own policy wins, but only when nothing was asked for that
		// it cannot express. A preset has to be honoured or refused, never
		// quietly dropped because a .vale.ini happened to sit above the target.
		if found, ok := findProjectConfig(f.Targets[0]); ok && f.Preset == "" {
			return found, nil
		}
		return generateConfig(e, languages, languages.Codes(), f.Preset)
	}

	codes := strings.Split(f.Languages, ",")
	if f.Languages == "all" {
		codes = languages.Codes()
	}
	for i := range codes {
		codes[i] = strings.TrimSpace(codes[i])
	}
	return generateConfig(e, languages, codes, f.Preset)
}

func generateConfig(e *env, languages registry.Languages, codes []string, presetName string) (string, error) {
	options := valeconf.Options{
		Header:     "Generated by stet. Edit languages.conf, not this file.",
		StylesPath: "../../styles",
	}
	for _, code := range codes {
		lang, ok := languages.Find(code)
		if !ok {
			return "", fmt.Errorf("stet: unknown language %q. Registered: %s",
				code, strings.Join(languages.Codes(), " "))
		}
		options.Languages = append(options.Languages, lang)
	}
	if english, ok := languages.Find("en"); ok {
		options.English = &english
	}

	if presetName != "" {
		preset, err := resolvePreset(e, codes, presetName)
		if err != nil {
			return "", err
		}
		options.Preset = preset
		// A language measured on one register has no base style to add.
		base := strings.ToUpper(preset.Lang) + "Base"
		if info, err := os.Stat(e.Layout.Style(base)); err == nil && info.IsDir() {
			options.BaseStyle = base
		}
	}

	if err := os.MkdirAll(e.Layout.ConfigCache(), 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(e.Layout.ConfigCache(), valeconf.CacheName(codes, presetName))
	return path, os.WriteFile(path, []byte(valeconf.Render(options)), 0o644)
}

// resolvePreset looks a preset up by the pair of language and code, because a
// code such as "docs" exists under more than one language. Asking for one
// outside the requested languages is refused with the reason rather than
// silently ignored, since its rules would not match the text.
func resolvePreset(e *env, codes []string, name string) (*registry.Preset, error) {
	presets, err := loadPresets(e)
	if err != nil {
		return nil, err
	}
	for _, code := range codes {
		if preset, ok := presets.Find(code, name); ok {
			return &preset, nil
		}
	}
	if preset, ok := presets.FindByCode(name); ok {
		return nil, fmt.Errorf(
			"stet: preset %q was measured for %q, which --lang did not ask for.\n"+
				"stet: its rules would not match this text. Add --lang %s, or drop --preset.",
			name, preset.Lang, preset.Lang)
	}
	var lines []string
	for _, p := range presets {
		lines = append(lines, fmt.Sprintf("  %-10s %s", p.Code, p.Description))
	}
	return nil, fmt.Errorf("stet: unknown preset %q. Available:\n%s", name, strings.Join(lines, "\n"))
}

func findProjectConfig(target string) (string, bool) {
	dir, err := filepath.Abs(target)
	if err != nil {
		return "", false
	}
	if info, err := os.Stat(dir); err != nil || !info.IsDir() {
		dir = filepath.Dir(dir)
	}
	for {
		candidate := filepath.Join(dir, ".vale.ini")
		if _, err := os.Stat(candidate); err == nil {
			return candidate, true
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", false
		}
		dir = parent
	}
}

// syncPackages downloads the Vale packages a config names, once. The marker
// beside the config is what makes it once rather than every run.
func syncPackages(e *env, vale, config string) {
	data, err := os.ReadFile(config)
	if err != nil {
		return
	}
	text := string(data)
	if !strings.HasPrefix(text, "Packages") && !strings.Contains(text, "\nPackages") {
		return
	}
	marker := filepath.Join(filepath.Dir(config), ".synced-"+filepath.Base(config))
	if _, err := os.Stat(marker); err == nil {
		return
	}
	cmd := exec.Command(vale, "--config="+config, "sync")
	if err := cmd.Run(); err == nil {
		os.WriteFile(marker, nil, 0o644)
	}
}

// settleWarmup reports the build rather than blocking on it in silence.
func settleWarmup(e *env, languages string) warmup.State {
	runner := build.New(e.Layout, e.Err)
	codes := warmupCodes(e, languages)

	switch state := runner.State(); state.Phase {
	case warmup.Cold:
		fmt.Fprintln(e.Err, "stet: first run, building rule data. This takes about 30 seconds.")
		runner.Run(codes)
	case warmup.Building:
		fmt.Fprintf(e.Err, "stet: warm-up running (%s). Waiting.\n", state.Message)
		deadline := time.Now().Add(waitForWarmup)
		for time.Now().Before(deadline) {
			time.Sleep(2 * time.Second)
			if runner.State().Phase != warmup.Building {
				break
			}
		}
	default:
		runner.Run(codes)
	}
	return runner.State()
}

func warmupCodes(e *env, languages string) []string {
	if languages != "" && languages != "all" {
		return strings.Split(languages, ",")
	}
	if registered, err := loadLanguages(e); err == nil {
		return registered.Codes()
	}
	return nil
}

func loadLanguages(e *env) (registry.Languages, error) {
	file, err := os.Open(e.Layout.Languages())
	if err != nil {
		return nil, fmt.Errorf("stet: cannot read the language registry: %w", err)
	}
	defer file.Close()
	return registry.ParseLanguages(file)
}

// loadPresets reads the preset registry, building it first when a fresh clone
// has none. Building reads committed data only, so it costs a moment and needs
// no network.
func loadPresets(e *env) (registry.Presets, error) {
	if _, err := os.Stat(e.Layout.Presets()); err != nil {
		runner := build.New(e.Layout, e.Err)
		for _, code := range []string{"uk", "en"} {
			runner.Run([]string{code})
		}
	}
	file, err := os.Open(e.Layout.Presets())
	if err != nil {
		return nil, fmt.Errorf("stet: cannot read the preset registry: %w", err)
	}
	defer file.Close()
	return registry.ParsePresets(file)
}

func listPresets(e *env) int {
	presets, err := loadPresets(e)
	if err != nil {
		fmt.Fprintln(e.Err, err)
		return 1
	}
	fmt.Fprintf(e.Out, "Available presets for --preset:\n\n")
	for _, p := range presets {
		note := ""
		if p.Preliminary {
			note = "  (preliminary)"
		}
		fmt.Fprintf(e.Out, "  %-10s %-4s %s%s\n", p.Code, p.Lang, p.Description, note)
	}
	fmt.Fprintf(e.Out, "\nA preset holds for the language it was measured on, in the second column.\n")
	fmt.Fprintf(e.Out, "A language without one is checked by its register-independent rules alone,\n")
	fmt.Fprintf(e.Out, "which is what running without --preset does.\n")
	return 0
}
