#!/usr/bin/env bash
# Generates ProseEN/Plain.yml from the LanguageTool English module.
#
# Thin next to the Ukrainian side, because ai-tells and write-good already carry
# English. Its value is the suggested replacement, which neither of those offers.
set -euo pipefail

OUT="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/styles/ProseEN}"
REF="${LT_REF:-master}"
URL="https://raw.githubusercontent.com/languagetool-org/languagetool/${REF}/languagetool-language-modules/en/src/main/resources/org/languagetool/rules/en/replace.txt"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

echo "stet: fetching LanguageTool English rules (${REF})" >&2
curl -fsSL "$URL" -o "$tmp/replace.txt"

mkdir -p "$OUT"
{
  printf '# Generated by generators/en-lt.sh from LanguageTool (LGPL-2.1). Do not edit.\n'
  printf 'extends: substitution\nmessage: "Use '"'"'%%s'"'"' instead of '"'"'%%s'"'"'."\nlevel: warning\nignorecase: true\nswap:\n'
  grep -v '^#' "$tmp/replace.txt" | grep -v '^[[:space:]]*$' \
    | awk -F'=' 'NF==2 {print $1 "\t" $2}' \
    | sed 's/\t\([^|;(]*\).*/\t\1/' \
    | sed 's/[[:space:]]*$//' \
    | awk -F'\t' '!seen[$1]++ && NF==2 && $2 != "" && $1 != $2 && $2 !~ /:/ {printf "  \"%s\": \"%s\"\n", $1, $2}'
} > "$OUT/Plain.yml"

printf 'stet: %s pairs -> Plain.yml\n' "$(grep -c '^  ' "$OUT/Plain.yml")" >&2
