#!/usr/bin/env bash
# Generates ProseUK substitution rules from the LanguageTool Ukrainian module.
#
# Fetched at run time rather than vendored: upstream is LGPL-2.1, and these are
# thousands of pairs maintained by that community for years. Anything we could
# type by hand would be a worse and staler subset.
set -euo pipefail

OUT="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/styles/ProseUK}"
REF="${LT_REF:-master}"
BASE="https://raw.githubusercontent.com/languagetool-org/languagetool/${REF}/languagetool-language-modules/uk/src/main/resources/org/languagetool/rules/uk"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

emit() {
  local src="$1" out="$2" level="$3" msg="$4" note="$5"
  {
    printf '# %s\n# Generated by generators/uk-lt.sh from LanguageTool (LGPL-2.1). Do not edit.\n' "$note"
    printf 'extends: substitution\nmessage: "%s"\nlevel: %s\nignorecase: true\nswap:\n' "$msg" "$level"
    # `wrong=right|alt; commentary` keeps only the first suggestion, since Vale
    # shows one replacement and the rest belong in a dictionary, not a linter.
    grep -v '^#' "$src" | grep -v '^[[:space:]]*$' \
      | awk -F'=' 'NF==2 && $1 !~ /[[:space:]]/ {print $1 "\t" $2}' \
      | sed 's/\t\([^|;(]*\).*/\t\1/' \
      | sed 's/[[:space:]]*$//' \
      | grep -v $'\tctx:' \
      | awk -F'\t' '!seen[$1]++ && NF==2 && $2 != "" && $1 != $2 && $2 !~ /:/ {printf "  \"%s\": \"%s\"\n", $1, $2}'
  } > "$out"
  printf 'stet: %s pairs -> %s\n' "$(grep -c '^  ' "$out")" "$(basename "$out")" >&2
}

echo "stet: fetching LanguageTool Ukrainian rules (${REF})" >&2
curl -fsSL "$BASE/replace_soft.txt" -o "$tmp/soft.txt"
curl -fsSL "$BASE/replace.txt" -o "$tmp/replace.txt"

mkdir -p "$OUT"
emit "$tmp/soft.txt" "$OUT/Preferred.yml" suggestion \
  "Краще: '%s' замість '%s'." "Softer preferences: the flagged form is not wrong, only weaker."
emit "$tmp/replace.txt" "$OUT/Barbarism.yml" warning \
  "Калька або барбаризм: '%s'. Українською: '%s'." "Calques and borrowings with a settled native form."
