package generate

import (
	"bufio"
	"fmt"
	"io"
	"sort"
	"strconv"
	"strings"
)

// Thresholds on excess frequency, machine rate over human rate. These come from
// the measurement in data/*-excess.tsv and are never chosen by hand.
const (
	baseMin   = 4.0 // high in every register: no preset needs to repeat it
	presetMin = 2.0 // below this the construction is not a marker in that register
)

var bands = []struct {
	Floor float64
	Level string
}{
	{8.0, "error"},
	{4.0, "warning"},
	{presetMin, "suggestion"},
}

// register describes one measured register. Brown category letters are opaque
// to anyone but the corpus, so the registry publishes a readable code instead.
type register struct {
	Style       string
	Code        string
	Description string
}

var registers = map[string]register{
	"H":        {"Official", "official", "ділове й офіційне"},
	"A":        {"Press", "press", "публіцистика та медіа"},
	"I":        {"Academic", "academic", "наукове й фахове"},
	"docs":     {"Docs", "docs", "технічна документація та інструкції"},
	"informal": {"Informal", "informal", "розмовне, підтримка, листування"},
	"fiction":  {"Fiction", "fiction", "художня література"},
}

// preliminary registers have a control corpus too small to trust.
var preliminary = map[string]bool{"fiction": true}

// Pattern is one row of a patterns file: a readable label and the expression
// the rule matches on.
type Pattern struct {
	Label string
	Expr  string
}

// Excess holds the measured ratio per construction per register.
type Excess map[string]map[string]float64

// RuleFile is one generated file, named relative to the styles directory.
type RuleFile struct {
	Dir     string
	Name    string
	Content string
	Count   int
}

// PresetSet is everything one language's measurement produces.
type PresetSet struct {
	Files []RuleFile
	// Rows are presets.conf lines for this language.
	Rows []string
}

// ParsePatterns reads a label-and-expression table in file order. Order is kept
// because it decides how constructions with equal excess are ranked.
func ParsePatterns(r io.Reader) ([]Pattern, error) {
	var out []Pattern
	scanner := bufio.NewScanner(r)
	scanner.Buffer(make([]byte, 0, 64*1024), 4*1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		label, expr, _ := strings.Cut(line, "\t")
		out = append(out, Pattern{Label: label, Expr: expr})
	}
	return out, scanner.Err()
}

// ParseExcess reads the measurement table and the comment lines above it. The
// comments carry the corpus sizes, which every generated file repeats so that a
// reader can see what the numbers rest on.
func ParseExcess(r io.Reader) (Excess, []string, error) {
	out := Excess{}
	var notes []string
	scanner := bufio.NewScanner(r)
	scanner.Buffer(make([]byte, 0, 64*1024), 4*1024*1024)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, "#") {
			notes = append(notes, strings.TrimLeft(line, "# "))
			continue
		}
		if line == "" {
			continue
		}
		fields := strings.Split(line, "\t")
		if len(fields) != 5 {
			return nil, nil, fmt.Errorf("excess table: want 5 columns, got %d in %q", len(fields), line)
		}
		value, err := strconv.ParseFloat(fields[4], 64)
		if err != nil {
			return nil, nil, fmt.Errorf("excess table: %q: %w", line, err)
		}
		if out[fields[0]] == nil {
			out[fields[0]] = map[string]float64{}
		}
		out[fields[0]][fields[1]] = value
	}
	return out, notes, scanner.Err()
}

type entry struct {
	Label  string
	Expr   string
	Level  string
	Excess float64
}

// Presets cuts measured constructions into a shared base and one rule set per
// register. A construction that runs high everywhere belongs to the base; one
// that runs high only in some registers belongs to those presets alone.
//
// lang is the style prefix, "UK" or "EN". source names the measurement file the
// generated header points back to.
func Presets(patterns []Pattern, excess Excess, notes []string, lang, source string) PresetSet {
	provenance := fmt.Sprintf("# Generated by stet from %s. Do not edit.\n", source)
	corpora := corpusNotes(notes)

	measured := measuredRegisters(excess)
	var solid []string
	for _, r := range measured {
		if !preliminary[r] {
			solid = append(solid, r)
		}
	}
	// A base means "high in every register", which says nothing when only one
	// register was measured. Such a language gets presets and no base.
	single := len(solid) < 2

	var base []entry
	perRegister := map[string][]entry{}

	for _, p := range patterns {
		ratios := excess[p.Label]
		if len(ratios) == 0 {
			continue
		}
		if !single && len(solid) > 0 {
			low := ratios[solid[0]]
			for _, r := range solid[1:] {
				if v := ratios[r]; v < low {
					low = v
				}
			}
			if low >= baseMin {
				base = append(base, entry{p.Label, p.Expr, levelFor(low), low})
				continue
			}
		}
		for _, r := range measured {
			if level := levelFor(ratios[r]); level != "" {
				perRegister[r] = append(perRegister[r], entry{p.Label, p.Expr, level, ratios[r]})
			}
		}
	}

	set := PresetSet{}
	if len(base) > 0 {
		header := provenance +
			fmt.Sprintf("# Excess of at least %.0fx in every solid register.\n", baseMin) +
			corpora + "\n"
		set.Files = append(set.Files, ruleFiles(lang+"Base", header, "Машинний зворот: '%s'", base)...)
	}

	for _, name := range measured {
		items := perRegister[name]
		if len(items) == 0 {
			continue
		}
		reg := describe(name)
		note := ""
		if preliminary[name] {
			note = "# Preliminary: the control corpus for this register is small.\n"
		}
		header := provenance + fmt.Sprintf("# Register: %s.\n", reg.Description) + note + corpora + "\n"
		dir := lang + reg.Style
		set.Files = append(set.Files, ruleFiles(dir, header, "Машинний зворот для цього стилю: '%s'", items)...)

		row := fmt.Sprintf("%s|%s|%s|%s", strings.ToLower(lang), reg.Code, dir, reg.Description)
		if preliminary[name] {
			row += "|preliminary"
		}
		set.Rows = append(set.Rows, row)
	}
	return set
}

// ruleFiles splits one register's constructions by severity. A single severity
// keeps the plain name, and several get one file each, because Vale takes one
// level per rule file.
func ruleFiles(dir, header, message string, items []entry) []RuleFile {
	byLevel := map[string][]entry{}
	var order []string
	for _, it := range items {
		if _, seen := byLevel[it.Level]; !seen {
			order = append(order, it.Level)
		}
		byLevel[it.Level] = append(byLevel[it.Level], it)
	}

	var out []RuleFile
	for _, level := range order {
		group := byLevel[level]
		sort.SliceStable(group, func(i, j int) bool { return group[i].Excess > group[j].Excess })

		name := "Slop.yml"
		if len(order) > 1 {
			name = "Slop-" + level + ".yml"
		}

		var b strings.Builder
		b.WriteString(header)
		b.WriteString("extends: existence\n")
		b.WriteString("message: \"" + message + "\"\n")
		b.WriteString("level: " + level + "\n")
		b.WriteString("ignorecase: true\nnonword: true\ntokens:\n")
		for _, it := range group {
			fmt.Fprintf(&b, "  # %s, надлишок %.1fx\n", it.Label, it.Excess)
			b.WriteString("  - '" + strings.ReplaceAll(it.Expr, "'", "''") + "'\n")
		}
		out = append(out, RuleFile{Dir: dir, Name: name, Content: b.String(), Count: len(group)})
	}
	return out
}

// MergeRegistry keeps the rows other languages wrote and replaces this
// language's own. Every language writes the same file.
func MergeRegistry(existing []string, lang string, rows []string) string {
	prefix := strings.ToLower(lang) + "|"
	keep := map[string]bool{}
	for _, line := range existing {
		if line != "" && !strings.HasPrefix(line, "#") && !strings.HasPrefix(line, prefix) {
			keep[line] = true
		}
	}
	for _, row := range rows {
		keep[row] = true
	}
	merged := make([]string, 0, len(keep))
	for line := range keep {
		merged = append(merged, line)
	}
	sort.Strings(merged)

	var b strings.Builder
	b.WriteString("# Generated by stet. lang|code|style|description\n")
	b.WriteString(strings.Join(merged, "\n"))
	b.WriteString("\n")
	return b.String()
}

func levelFor(excess float64) string {
	for _, band := range bands {
		if excess >= band.Floor {
			return band.Level
		}
	}
	return ""
}

func measuredRegisters(excess Excess) []string {
	seen := map[string]bool{}
	for _, row := range excess {
		for name := range row {
			seen[name] = true
		}
	}
	out := make([]string, 0, len(seen))
	for name := range seen {
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}

func describe(name string) register {
	if r, ok := registers[name]; ok {
		return r
	}
	title := name
	if title != "" {
		title = strings.ToUpper(title[:1]) + title[1:]
	}
	return register{Style: title, Code: name, Description: name}
}

func corpusNotes(notes []string) string {
	var kept []string
	for _, n := range notes {
		if strings.HasPrefix(n, "machine") || strings.HasPrefix(n, "control") {
			kept = append(kept, "# "+n)
		}
	}
	return strings.Join(kept, "\n")
}
